### ISSUE TITLE
Кто-нибудь использовал этот компонент?

### ISSUE THREAD

**Issue by wberdnik** [Mikecoon/yii2-yandex-kassa-api#2]
README.md:

>  if ($order->payment_type == $order::PAYTYPE_ONLINE) {
>            return $this->redirect(['order/create-payment', 'id' =>$order->id]);
>         } else {
>             return $this->redirect(['order/success']);
>         }

1. Что такое PAYTYPE_ONLINE ?
2. Как понимать   $order::  ?
3. Что это за action такой - редирект на создание платежа и на подтверждение платежа сразу?
4. Почему @throw нигде не обрабатываются для $client->createPayment() и т.д.
5. Почему нет hook-а в случае неоплаты клиентом в ConfirmPaymentAction
Например так
 ```
 if (!$request->object->paid) {
               if ($this->notPaidConfirm)
                   call_user_func_array($this->notPaidConfirm, [$order]);
            return false;
        }
```

**Comment by Maclay74** [comment]
1. PAYTYPE_ONLINE это проекто-зависимый код. Пример, проще говоря.
2. $order - Это, очевидно, модель, реализующая интерфейс OrderInterface.
3. Опять же, экшен проверяет, нужно ли давать пользователю оплачивать онлайн или нет и показывает в зависимости от этого нужную страницу.
4. Потому что отлавливать исключения - задача разработчика?
5. Не было необходимости. Считаете нужным - предлагайте PR, добавим.

**Comment by wberdnik** [comment]
PAYTYPE_ONLINE - наверное должно быть, что-то типа FOR_PAY, SHOULD_PAY, NEED_PAY. Это же пример, через него объясняют...
2.   СТАТИЧЕСКОЕ имя класса в переменную  $order. И обратиться к константе $order::PAYTYPE_ONLINE. Это обфускатор? Случай экзотический и не всегда работает.
3. В смысле, если не нужно оплачивать, то как в программе-шутке "Ваш диск форматируется". Только здесь - "Вы только что заплатили деньги. Поздравляем!". Как еще можно понимать success для order?
4. Вы же actions предоставляете для вызова со стороны Яндекса и клиента, а не API. Разработчик должен Yii переписывать, что бы исключения ловить?
5. Уже предложил.

**Comment by Maclay74** [comment]
1. В конкретном моем случае, была константа оплаты онлайн или при получении.
2. У меня создается ордер из формы или каким-то другим образом. Зачем делать его статическим, если он передается в замыкания? Еще раз, это компонент именно оплаты через Яндекс, не система управления заказами. 
3. Я подозреваю, что у вас есть только онлайн оплата. Поэтому в конкретном вашем случае, мы можете получить success только после удачной оплаты.
4. Вы видите, что исключения могут быть в двух случаях - когда вы подсовываете не тот интерфейс и когда вы вручную отвергаете оплату через замыкание. Так что вам мешает в замыкании предусмотреть это поведение?
5. Не вижу PR.

**Comment by wberdnik** [comment]
1 И я о том, что это у вас конкретно. А readme - он для остальных.
2. Вы меня не слышите. У вас переменная $order и оператор :: - разрешения области видимости (класса) http://php.net/manual/ru/language.oop5.paamayim-nekudotayim.php. В вашем случае $order может содержать только имя статического элемента. Согласно psr - заглавные буквы обозначают константу.
3. А зачем показывать success, если оплата не нужна?
4. Дурной тон - делать предположения по поводу чужой библиотеки. В библиотеке написано, что вызывающая сторона должна отловить список исключений - значит их нужно отлавливать. Ваши замыкания (Правильно: Хук (перехват, подписка) через анонимную функцию. Вы не используете замыкания - у вас нет use ) здесь ни при чем.
5. Ваше право. Из-за большого количества ошибок ( не только здесь перечисленных) я давно откатил компонент и сделал по-своему.

**Comment by Maclay74** [comment]
1. Так мне заголовок добавить о том, что это пример? Это решит проблему?
2. В моем случае, $order содержит объект класса, который реализует интерфейс. И это, разумеется, константа. В чем ошибка? Куда вы предлагаете их выносить и зачем?
3. Господи, чтобы человек увидел, что его заказ принят в обработку.
4. Вообще бессмыслица. Исключение вызываете вы, возвращая в замыкании (кстати, бред про use это отдельная история, [читаем здесь](http://php.net/manual/ru/functions.anonymous.php)) false и тогда выбрасывается исключение. Если этого не сделать, обработать как-то иначе, то и исключения не будет.
5. И это ваше право. Один из главных принципов Open Source - критикуешь-предлагай.

**Comment by wberdnik** [comment]
1. Прошу понять правильно. Когда переходишь от старого HTTP интерфейса к API - сложно сразу въехать где - какие URL. В HTTP их на 1 больше. Естественно первый путь - сделать все по аналогии и посмотреть как работает. На момент открытия этого обсуждения я не понимал смысл примера. Сейчас понятно - был готовый проект - его просто выложили. Получилось как получилось. Совершенно серьезно - это пример не нужен, он мешает пониманию, а не помогает. Отсюда и критика. Гораздо лучше было бы расписать - какой URL зачем нужен. Тот, что в config - это адрес возврата на сайт из Я.Кассы, для оплаты - сначала делаем запись в Orders, а потом переходим на  Controller/create-payment. В настройках Я.Кассы пишем Controller/notify. Ваш пример только запутывает. Первое, что я подумал - надо делать еще один action с приведенным кодом. Серьезно.
2. Через объект к интерфейсу. Теперь понятно. В Yii такой код не встретишь.  Хотя вроде бы - логично. Весьма и весьма специфично - проверю.
3. Какой человек, в какую обработку? Если бы не это обсуждение - пойди догадайся.
4. Исключения выбрасывают throw и перехватывают catch. Их не вызывают. Замыкание — это функция, охватывающая или замыкающая текущую область видимости. Замыкание основано на лексической области видимости. Наверное можно долго дискутировать, но то что в php лямбда передается объектом closure, еще не означает реализацию замыкания.
Но речь не об этом. Исключения возникают не всегда по воле программиста. Может и железка сбой дать. У вас с этим совсем слабенько. Например ConfirmPaymentAction выбрасывает HttpException 500 код. Для маленьких сайтов читать логи наверное интересно, но не продуктивно. Здесь же `$request = json_decode(file_get_contents('php://input')); $invoceId = $request->object->id;` Опять смотрим в логах, если JSON сломался. Хотя - все это дело вкуса. Однако в CreatePaymentAction TooManyRequestsException можно было бы обработать и предложить клиенту зайти позже....

Давайте закрывать тему. У меня свои Open Source наработки есть - "руки не доходят". Поэтому простите - не помогу.

**Comment by Maclay74** [comment]
Я согласен, этот компонент я написал по мере работы над проектом и выложил, чтобы, в первую очередь, потому самому использовать, поэтому он не слишком хорошо документирован.

**Comment by wberdnik** [comment]
Однако, никто кроме вас ничего подобного не делал, что похвально.
